# Generated by Django 5.0.3 on 2024-04-07 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_itemreview_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemReview',
            new_name='ItemReviewList',
        ),
    ]
