# Generated by Django 5.0.3 on 2024-04-11 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_onsalelits'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OnSaleLits',
            new_name='OnSaleList',
        ),
    ]
