# Generated by Django 5.0.3 on 2024-04-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_onsalelits_onsalelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemreviewlist',
            name='item_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
