# Generated by Django 5.0.3 on 2024-04-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_itemreviewlist_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemreviewlist',
            name='review_text',
            field=models.TextField(default=''),
        ),
    ]
