# Generated by Django 5.0.3 on 2024-04-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_itemreviewlist_review_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellitemlist',
            name='item_price',
            field=models.IntegerField(default=0),
        ),
    ]
